In [4]:
# standarization
import numpy as np
x = np.random.random(4)     # values between 0 and 1
print("x:\n", x)
print (f"mean: {np.mean(x):.2f}, std: {np.std(x):.2f}")
x_standarized = (x - np.mean(x)) / np.std(x)
print("x_standarized:\n", x_standarized)
print (f"mean: {np.mean(x_standarized):.2f}, std {np.std(x_standarized):.2f}")

x:
 [0.56237851 0.47500025 0.42595754 0.61621025]
mean: 0.52, std: 0.07
x_standarized:
 [ 0.57398837 -0.60633401 -1.26881226  1.3011579 ]
mean: 0.00, std 1.00


In [8]:
# Min-max
x = np.random.random(4)
print ("x:", x)
print (f"min: {x.min():.2f}, max: {x.max():.2f}")
x_scaled = (x - x.min()) / (x.max() - x.min())
print ("x_scaled:", x_scaled)
print (f"min: {x_scaled.min():.2f}, max: {x_scaled.max():.2f}")

x: [0.89055788 0.4196543  0.2386616  0.88923433]
min: 0.24, max: 0.89
x_scaled: [1.         0.27764034 0.         0.99796971]
min: 0.00, max: 1.00


In [10]:
# Binning
x = np.random.random(4) # values between 0 and 1
print ("x:", x)
bins = np.linspace(0, 1, 5) # bins between 0 and 1
print ("bins:", bins)
binned = np.digitize(x, bins)
print ("binned:", binned)

x: [0.74383528 0.77617452 0.18129342 0.31054698]
bins: [0.   0.25 0.5  0.75 1.  ]
binned: [3 4 1 2]


### Codificacion

In [ ]:
# PCA
from sklearn.decomposition import PCA
X = np.array([[-1, -1, 3], [-2, -1, 2], [-3, -2, 1]])
pca = PCA(n_components=2)
pca.fit(X)
print (pca.transform(X))
print (pca.explained_variance_ratio_)
print (pca.singular_values_)

[[ 1.44245791 -0.1744313 ]
 [ 0.1148688   0.31291575]
 [-1.55732672 -0.13848446]]
[0.96838847 0.03161153]
[2.12582835 0.38408396]


In [18]:
# Counts (ngram)
from sklearn.feature_extraction.text import CountVectorizer
y = [
    "acetyl acetone",
    "acetyl chloride",
    "chloride hydroxide",
]
vectorizer = CountVectorizer()
y = vectorizer.fit_transform(y)
print (vectorizer.get_feature_names_out())
print (y.toarray())
# 💡 Repeat above with char-level ngram vectorizer
# vectorizer = CountVectorizer(analyzer='char', ngram_range=(1, 3)) # uni, bi and trigrams


['acetone' 'acetyl' 'chloride' 'hydroxide']
[[1 1 0 0]
 [0 1 1 0]
 [0 0 1 1]]
